name: Build CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node_modules
      run: yarn install
    - name: Test
      run: yarn test
      env:
        CI: true
    - name: Build
      run: yarn build
    - name: Send coverage (only Node 12.x)
      if: startsWith(matrix.node-version, '12.')
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  
  publish:
    if: github.ref == 'refs/heads/master'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install node_modules
      run: yarn install
    - name: Build
      run: yarn build
    - name: Semantic Release (publish to npm)
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
