name: Build CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn install
    - name: Test
      run: yarn test
      env:
        CI: true
    - name: Build
      run: yarn build
    - name: Coverage
      if: startsWith(matrix.node-version, '12.')
      run: bash <(curl -s https://codecov.io/bash)
  
  
  publish:
    if: github.ref == 'refs/heads/master'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install modules
      run: yarn install
    - name: Build
      run: yarn build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
